# Generated by Django 4.2.3 on 2023-08-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sust_book_portal', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='archived_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='book_files/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sust_book_portal.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sust_book_portal.semester')),
            ],
        ),
    ]
